/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing2;

/**
 *
 * @author USER
 */
public class KonfirmasiBriva extends javax.swing.JFrame {

    /**
     * Creates new form KonfirmasiBriva
     */
    public KonfirmasiBriva() {
        initComponents();
        KonfirmasiBrivaModel nobriva = new KonfirmasiBrivaModel();
        briva.setText("NO. BRIVA      :       "+nobriva.getNobriva());
        KonfirmasiBrivaModel institusi = new KonfirmasiBrivaModel();
        institusip.setText("INSTITUSI      :       "+institusi.getInstitusi());
        KonfirmasiBrivaModel nama = new KonfirmasiBrivaModel();
        namap.setText("NAMA         :       "+nama.getNama());
        KonfirmasiBrivaModel keterangan = new KonfirmasiBrivaModel();
        ket.setText("KETERANGAN     :       "+keterangan.getKeterangan());
        KonfirmasiBrivaModel tagihan = new KonfirmasiBrivaModel();
        tagih.setText("TAGIHAN         :       "+tagihan.getTagihan());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        briva = new javax.swing.JLabel();
        institusip = new javax.swing.JLabel();
        namap = new javax.swing.JLabel();
        ket = new javax.swing.JLabel();
        tagih = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        briva.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        briva.setForeground(new java.awt.Color(255, 255, 255));
        briva.setText("NO. BRIVA        : ");
        jPanel1.add(briva);
        briva.setBounds(50, 180, 400, 50);

        institusip.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        institusip.setForeground(new java.awt.Color(255, 255, 255));
        institusip.setText("INSTITUSI          :");
        jPanel1.add(institusip);
        institusip.setBounds(50, 230, 390, 40);

        namap.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        namap.setForeground(new java.awt.Color(255, 255, 255));
        namap.setText("NAMA                :");
        jPanel1.add(namap);
        namap.setBounds(50, 280, 380, 40);

        ket.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        ket.setForeground(new java.awt.Color(255, 255, 255));
        ket.setText("KETERANGAN :");
        jPanel1.add(ket);
        ket.setBounds(50, 320, 330, 50);

        tagih.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tagih.setForeground(new java.awt.Color(255, 255, 255));
        tagih.setText("TAGIHAN          :  ");
        jPanel1.add(tagih);
        tagih.setBounds(50, 380, 520, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("PROSES PEMBAYARAN ?");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(540, 450, 300, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("YA ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 450, 140, 31);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("TIDAK  ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(860, 520, 140, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PT. BANK  RAKYAT  INDONESIA");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(240, 30, 540, 80);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PEMBAYARAN  BRIVA");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 80, 390, 80);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new PembayaranBriva().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new Briva().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBriva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBriva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBriva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiBriva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfirmasiBriva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel briva;
    private javax.swing.JLabel institusip;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ket;
    private javax.swing.JLabel namap;
    private javax.swing.JLabel tagih;
    // End of variables declaration//GEN-END:variables
}
