/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing2;

/**
 *
 * @author USER
 */
public class KonfirmasiTransfer extends javax.swing.JFrame {

    /**
     * Creates new form KonfirmasiTransfer
     */
    public KonfirmasiTransfer() {
        initComponents();
        KonfirmasiTransferModel bank = new KonfirmasiTransferModel();
        bankAsal.setText("BANK      :       "+bank.getBank());
        KonfirmasiTransferModel tujuan = new KonfirmasiTransferModel();
        tujuanBank.setText("TUJUAN      :       "+bank.getTujuan());
        KonfirmasiTransferModel nama = new KonfirmasiTransferModel();
        namap.setText("NAMA         :       "+bank.getNama());
        KonfirmasiTransferModel rek = new KonfirmasiTransferModel();
        norek.setText("NO. REF      :       "+bank.getRek());
        KonfirmasiTransferModel jumlah = new KonfirmasiTransferModel();
        um.setText("JUMLAH         :       "+bank.getJumlah());
        KonfirmasiTransferModel admin = new KonfirmasiTransferModel();
        adminb.setText("ADMIN BANK  :       "+bank.getAdmin());
        KonfirmasiTransferModel total = new KonfirmasiTransferModel();
        tot.setText("TOTAL      :       "+bank.getTotal());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        bankAsal = new javax.swing.JLabel();
        tujuanBank = new javax.swing.JLabel();
        namap = new javax.swing.JLabel();
        norek = new javax.swing.JLabel();
        um = new javax.swing.JLabel();
        adminb = new javax.swing.JLabel();
        tot = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TRANSFER ATM");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(380, 50, 270, 70);

        bankAsal.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        bankAsal.setForeground(new java.awt.Color(255, 255, 255));
        bankAsal.setText("BANK                 : ");
        jPanel1.add(bankAsal);
        bankAsal.setBounds(50, 140, 400, 50);

        tujuanBank.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tujuanBank.setForeground(new java.awt.Color(255, 255, 255));
        tujuanBank.setText("TUJUAN             :");
        jPanel1.add(tujuanBank);
        tujuanBank.setBounds(50, 190, 390, 40);

        namap.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        namap.setForeground(new java.awt.Color(255, 255, 255));
        namap.setText("NAMA                :");
        jPanel1.add(namap);
        namap.setBounds(50, 230, 380, 40);

        norek.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        norek.setForeground(new java.awt.Color(255, 255, 255));
        norek.setText("NO. REF             :");
        jPanel1.add(norek);
        norek.setBounds(50, 270, 330, 50);

        um.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        um.setForeground(new java.awt.Color(255, 255, 255));
        um.setText("JUMLAH            :  ");
        jPanel1.add(um);
        um.setBounds(50, 320, 520, 30);

        adminb.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        adminb.setForeground(new java.awt.Color(255, 255, 255));
        adminb.setText("ADMIN BANK  :");
        jPanel1.add(adminb);
        adminb.setBounds(50, 360, 480, 30);

        tot.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tot.setForeground(new java.awt.Color(255, 255, 255));
        tot.setText("TOTAL               : ");
        jPanel1.add(tot);
        tot.setBounds(50, 400, 460, 28);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("APAKAH ANDA INGIN MELAKUKAN TRANSAKSI LAIN ?");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(200, 450, 640, 40);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("YA ->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(860, 450, 140, 31);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("TIDAK  ->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(860, 520, 140, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HalamanAkhir().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonfirmasiTransfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonfirmasiTransfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adminb;
    private javax.swing.JLabel bankAsal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel namap;
    private javax.swing.JLabel norek;
    private javax.swing.JLabel tot;
    private javax.swing.JLabel tujuanBank;
    private javax.swing.JLabel um;
    // End of variables declaration//GEN-END:variables
}
