/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing2;

/**
 *
 * @author USER
 */
public class PenarikanTunai extends javax.swing.JFrame {

    /**
     * Creates new form PenarikanTunai
     */
    public PenarikanTunai() {
        initComponents();
        PenarikanTunaiModel penarikantunai = new PenarikanTunaiModel();
        sisa.setText("Rp "+penarikantunai.getPenarikantunai());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sisa = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        Ps = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1020, 600));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MASUKKAN  JUMLAH PENARIKAN TUNAI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(180, 50, 720, 60);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("YANG  ANDA INGINKAN");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 100, 420, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("(DALAM  KELIPATAN  Rp  50.000)");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(240, 120, 550, 80);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("MAKSIMAL  Rp 1.250.000");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 180, 430, 50);

        sisa.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        sisa.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sisa);
        sisa.setBounds(30, 370, 440, 50);

        jButton1.setBackground(new java.awt.Color(0, 102, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("TEKAN  JIKA  BENAR  -->");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(670, 380, 340, 37);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TEKAN UNTUK  PEMBATALAN  TEKAN  CANCEL");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(470, 500, 550, 40);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("TEKAN  JIKA  SALAH  -->");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(670, 440, 340, 40);

        Ps.setBackground(new java.awt.Color(0, 102, 255));
        Ps.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        Ps.setForeground(new java.awt.Color(255, 255, 255));
        Ps.setText(" ");
        Ps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PsActionPerformed(evt);
            }
        });
        jPanel1.add(Ps);
        Ps.setBounds(400, 230, 220, 40);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1020, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        PenarikanTunaiModel ps = new PenarikanTunaiModel();
        InformasiSaldoModel saldo = new InformasiSaldoModel();
        String jmlh = Ps.getText();
        double jmlh2 = Double.parseDouble(jmlh);
        ps.penarikantunai = jmlh2;
        double s = Double.parseDouble(saldo.getSaldo());
        double hasil = s- ps.penarikantunai;
        if(Ps != null){
            sisa.setVisible(true);
            sisa.setText("SISA SALDO ANDA : Rp "+hasil);
        }else{
            sisa.setVisible(false);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new HalamanUtama().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void PsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PenarikanTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PenarikanTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PenarikanTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PenarikanTunai.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PenarikanTunai().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ps;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel sisa;
    // End of variables declaration//GEN-END:variables
}
